Repository wecode-bootcamp-korea/20-2nd-WattaTaxi-frontend, pull requests merged in 2021-06, with the labels that each got.

#7 [20기 김예슬] Modify : conflict 해결, 불필요한 주석 제거
  package-lock.json
  package.json
  src/Components/LineTo.js
  src/Components/Search/SearchBar.js
  src/Pages/List/Components/Checkbox.js
  src/Pages/List/Components/Course.js
  src/Pages/List/Components/fontStyle.js
  src/Pages/List/List.js
  src/Pages/Main/Components/SearchMenu.js
  src/Pages/Main/Main.js
  src/Routes.js
  src/styles/theme.js
Labels: Status: 리뷰 요청

#9 [20기 최원근] Add : main 페이지 구현
  package-lock.json
  package.json
  public/data/MockData.json
  public/images/63-bilding.png
  public/images/banner.png
  public/images/banner1.png
  public/images/banner2.png
  public/images/banner3.png
  public/images/banner4.png
  public/images/dongjag-yeog.png
  public/images/driver1.png
  public/images/driver2.png
  public/images/driver3.png
  public/images/driver4.png
  public/images/facebook.png
  public/images/footer.png
  public/images/headrButton.png
  public/images/ichon-naluteo.png
  public/images/insta.png
  public/images/leftArrow.png
  public/images/location.png
  public/images/mang-won.png
  public/images/prevBtn.png
  public/images/prevButton.png
  public/images/profile.png
  public/images/rank.png
  public/images/recent.png
  public/images/rightArrow.png
  public/images/seobing-go.png
  public/images/seon-yudo.png
  public/images/seoul-forest.png
  public/images/yeouinalu.png
  public/images/youtube.png
  src/Pages/Main/Main.js
  src/Pages/Main/components/MainBanner.js
  src/Pages/Main/components/MainFooter.js
  src/Pages/Main/components/MainForm.js
  src/Pages/Main/components/MainHeader.js
  src/Pages/Main/components/MainTaxi.js
  src/Routes.js
Labels: Status: 리뷰 요청

#10 [20기 이다슬] Add : 댓글 기능 구현, 택시 기사 상세페이지 fetch setting
  public/data/review.json
  public/data/taxidriver.json
  public/index.html
  src/Components/Token.js
  src/Pages/DetailTaxiDriver/Components/DetailComments.js
  src/Pages/DetailTaxiDriver/Components/DetailDriverInfo.js
  src/Pages/DetailTaxiDriver/Components/DetailReserve.js
  src/Pages/DetailTaxiDriver/DetailTaxiDriver.js
  src/Pages/Main/components/MainTaxi.js
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청

#11 [20기 윤세용] Add: (발표용merge)로그인 회원가입 리뷰반영+ route.js, config.js 수정
  public/index.html
  src/Components/GetSetToken.js
  src/Pages/Login/Login.js
  src/Pages/Main/components/MainBanner.js
  src/Routes.js
  src/config.js
Labels: Status: 수정 요청

#12 [20기 윤세용]Add : (발표용merge)Nav 리뷰반영 + 검색바 애니메이션 구현
  src/Components/GetSetToken.js
  src/Components/Nav.js
Labels: Status: Rebase 요청, Status: 리뷰 요청

#15 [20기 김예슬] Modify: 검색바
  src/Components/Search/Components/Date.js
  src/Components/Search/Components/DateInput.js
  src/Components/Search/Components/Location.js
  src/Components/Search/Components/LocationModal.js
  src/Components/Search/Components/Passenger.js
  src/Components/Search/SearchBar.js
  src/Pages/Main/Components/SearchMenu.js
  src/Pages/Main/MainTaxi.js
  src/config.js
Labels: Status: 리뷰 요청

#16 [20기 이다슬] Modify : 예약내역페이지 레이아웃 , fetch setting
  public/data/reserve.json
  src/Pages/Reserve/Reserve.js
Labels: Status: 리뷰 요청

#17 [20기 김예슬] Modify: Loading Page
  src/Pages/Loading/Components/Destination.js
  src/Pages/Loading/Components/DestinationBox.js
  src/Pages/Loading/Loading.js
  src/config.js
Labels: Status: 리뷰 요청
